// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB--YbbQAb8NCLAXw7PNCzLcfsOqv261Cc',
    appId: '1:216707103164:web:3c855666f2feeabbdc53b9',
    messagingSenderId: '216707103164',
    projectId: 'arabic-tutor-vs74s',
    authDomain: 'arabic-tutor-vs74s.firebaseapp.com',
    databaseURL: 'https://arabic-tutor-vs74s-default-rtdb.firebaseio.com',
    storageBucket: 'arabic-tutor-vs74s.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANdmaEAkAdEJAVoNg1yKVDT0b3I_AlQ2Q',
    appId: '1:216707103164:android:e367bac9b509b6e0dc53b9',
    messagingSenderId: '216707103164',
    projectId: 'arabic-tutor-vs74s',
    databaseURL: 'https://arabic-tutor-vs74s-default-rtdb.firebaseio.com',
    storageBucket: 'arabic-tutor-vs74s.firebasestorage.app',
  );
}
